### ISSUE TITLE
Write unit tests - Bug fighting

### ISSUE THREAD

**Issue by Naarakah** [remi-dupre/dungeon-battle#10]
Testing framework integrated in build system, including tests.

**Comment by Naarakah** [comment]
We have a continuous integration system as well as unit tests.

**Comment by esum** [comment]
Tests should be executed by the `tests` rule of the Makefile and not just compiled.
The include directive could be relevant here.

**Comment by esum** [comment]
Fixed with fe21aac14db52e811344e663aeafa2d16cf34501
