### ISSUE TITLE
Map generation

### ISSUE THREAD

**Issue by remi-dupre** [remi-dupre/dungeon-battle#20]

**Comment by Naarakah** [comment]
We should enhance more the procedural generation of the map.

**Comment by dbaelde** [comment]
On this topic, note that the project spec says that the game should be played on a _series_ of levels. Hence the "Board" goal is not completed until the world has more than one level.

That being said, congratulations on the good looking and varied generated levels!

**Comment by remi-dupre** [comment]
Thank you :)

This issues as been fixed in the "game" part, when we reach an "UpStair" we can interact with it to generate the next level (a4c287d10457c7ad122e35b4f7e6922998f116a8 and 56cbe62c6e6a59eb308634110ee88a0cda95bcc4).
