### ISSUE TITLE
Dependencies in Makefile

### ISSUE THREAD

**Issue by dbaelde** [remi-dupre/dungeon-battle#27]
The Makefile is missing dependencies, causing builds to fail unless "make clean" is done first. A possible way to fix this (besides setting dependencies manually) is described here: https://stackoverflow.com/questions/313778/generate-dependencies-for-a-makefile-for-a-project-in-c-c

**Comment by Naarakah** [comment]
Fixed in 39e9f0ae6aa8118b4952f4cef211b8bd052a1dc2 and 35ed62c75f4a0b8a0253cfde712a9a5ee0035015
