### ISSUE TITLE
Decide the structure of the program

### ISSUE THREAD

**Issue by remi-dupre** [remi-dupre/dungeon-battle#3]
- [x] Configuration structure
- [x] Definission of a structure representing the game
- [x] Definission of how to represent maps, games and all gameplay elements

**Comment by esum** [comment]
Fixed by 084a48153fb94604b7824a95bc8d4f2128146086, 58dee1bdce45df5ca4e3fcaac240a003447ace77 and 7a8d5dae462c049d637a3ebe29f754f481225881
